name: crawl 

on: [push]
#  schedule:
#    - cron: '*/15 * * * *'  #every 15 minite we crawl

jobs:
  crawl-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: git config --global user.email "3298520845@qq.com"
      - run: git config --global user.name "yuner2001"
      - run: git pull origin main
      - run: python crawl.py
      - run: git add *
      - run: git commit -m 'sipder commit'
      - run: git push origin main
      