name: crawl 

on: [push]
#  schedule:
#    - cron: '*/15 * * * *'  #every 15 minite we crawl

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      # install the old version
      - run: pip uninstall pyOpenSSL==22.1.0
      - run: pip install pyOpenSSL==22.0.0
      - run: python crawl.py
      - run: python send.py