name: crawl 

on: [push]
#  schedule:
#    - cron: '*/15 * * * *'  #every 15 minite we crawl

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: echo 'Finished!'